linters:
  enable:
  - asasalint
  - bidichk
  - bodyclose
  - durationcheck
  - errname
  - errorlint
  - exportloopref
  - gocheckcompilerdirectives
  - importas
  - makezero
  - mirror
  - misspell
  - musttag
  - nilnil
  - revive
  - tenv
  - thelper
  - tparallel
  - unconvert
  - wastedassign
  - zerologlint
