on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    - release/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - uses: actions/setup-node@v3
      with:
        node-version: "18.17"
    # Always save cache for apt/lists, as the playwright install --with-deps
    # below will do an apt-get upgrade under the hood, which we want to save no
    # matter the success of subsequent step success.
    #
    # https://github.com/actions/cache/tree/main/save#always-save-cache
    - uses: actions/cache@v3
      if: always()
      with:
        path: /var/lib/apt/lists
        key: ${{ runner.os }}-apt
    - uses: actions/cache@v3
      with:
        path: |
          /home/runner/.cache/ms-playwright-go
          /home/runner/.cache/ms-playwright
        key: ${{ runner.os }}-playwright
    - run: npm install playwright@1.37.1
    - run: go mod download
    - run: go run github.com/playwright-community/playwright-go/cmd/playwright install --with-deps
    - env:
        LOG_LEVEL: trace
        TEST_LIVE_HTTP: "true"
      run: go test -v ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: codecov/codecov-action@v3
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: trufflesecurity/trufflehog@v3.48.0
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=10m
  just-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.9.0
    - run: go install github.com/rhysd/actionlint/cmd/actionlint@v1.6.25
    - run: python3 -m pip install yamllint
    - env:
        JUST_REPO_URL: "https://github.com/casey/just/releases/download"
        JUST_VERSION: "1.14.0"
        JUST_PLATFORM: "x86_64-unknown-linux-musl"
        JUST_SHA256: "19848d0282e95f30188305b1bbd5a087793e5c6f27f5ac98207ab256027183df"
      run: |
        set -euxo pipefail
        TMP_DIR=$(mktemp -d)
        DOWNLOAD_URL="${JUST_REPO_URL}/${JUST_VERSION}/just-${JUST_VERSION}-${JUST_PLATFORM}.tar.gz"
        curl -L "$DOWNLOAD_URL" -o "$TMP_DIR/just.tar.gz"
        ls -lhF "$TMP_DIR/just.tar.gz"
        echo "$JUST_SHA256 $TMP_DIR/just.tar.gz" | sha256sum --check
        tar xvf "$TMP_DIR/just.tar.gz" -C "$TMP_DIR"
        mv "$TMP_DIR/just" /usr/local/bin/
        rm -rf "$TMP_DIR"
        just --version
    - run: just lint
